### ISSUE TITLE
Add API versioning

### ISSUE THREAD

**Issue by MarkAD88** [EthosLending/HelloWorldService#2]
In order to allow for regular updates of the API as business needs arise it is important to protect existing API consumers from changes that may break their current implementation.

In order to address this, API versioning should be part of the standard RESTful service template.

Versioning should be accomplished using standard URL semantics as follows:

```http://host:port/api/v1/controller```

The standard API versioning headers - supported api-supported-versions and api-deprecated-versions  - should be included in every response.

Use of the Microsoft.AspNetCore.Mvc.Versioning NuGet ([nuget.org](https://www.nuget.org/packages?q=Microsoft.AspNetCore.Mvc.Versioning)) ([GitHub](https://github.com/Microsoft/aspnet-api-versioning)) package makes implementation and use of versioning extremely simple and is the recommended approach.

**Comment by mikebz** [comment]
feature just added.  Thank you!
