### ISSUE TITLE
Add automatic API documentation and testing UI

### ISSUE THREAD

**Issue by MarkAD88** [EthosLending/HelloWorldService#3]
Documentation is key to minimizing the amount of time it takes a developer to understand an API.  Automatically generating documentation based on controller, method and parameter comments minimizes the impact that this documentation has on the developers of the API itself.

In order to provide the best possible developer experience, both for the developer writing the API and the developer consuming the API, the template should make use of [Swashbuckle](https://github.com/domaindrivendev/Swashbuckle)

This package, in conjunction with [Swagger](https://swagger.io), allows for a documentation and testing UI to be automatically generated as part of the build process with only a minor amount of work required.

**Comment by mikebz** [comment]
feature just added, thank you!
