### ISSUE TITLE
Add Token Authorization

### ISSUE THREAD

**Issue by MarkAD88** [EthosLending/HelloWorldService#4]
Security is a key component of any micro-service based architecture and as such it needs to be part of the micro-service template.

Use of the [IdentityServer4.AccessTokenValidation](https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation) NuGet package is recommended as the company has standardized on IdentityServer4 at this time.

The template should use https://login.ethoslending.com as the default authentication server and the URL value needs to be read from configuration so that it can be changed during deployment.

**Comment by mikebz** [comment]
The change to address is is created and awaiting PR review.
